#version: "3.9"
services:
  utf8-fixer:
    image: ghcr.io/tommypopescu/subscode:latest   # înlocuiește cu org/repo
    container_name: utf8-sub-fixer
    restart: unless-stopped
    environment:
      WATCH_MODE: "scan"                   # sau "scan"
      SCAN_INTERVAL_S: "3600"
      FILE_EXTS: "srt,ass,ssa,vtt,sub,txt"
      WATCH_PATHS: "/sources/movies,/sources/series,/sources/downloads"
      BACKUP_DIR: "/backup"
      BACKUP_ORIGINAL: "true"
      BACKUP_CONVERTED: "true"
      NORMALIZE_RO: "true"
      NORMALIZE_NFC: "true"
      REMOVE_BOM: "true"
    volumes:
      - /srv/mergerfs/3TB_merger/downloads/downloads/movie/:/sources/movies:rw
      - /srv/mergerfs/3TB_merger/downloads/downloads/series/:/sources/series:rw
     # - /data/downloads:/sources/downloads:rw
     # - /srv/mergerfs/3TB_merger/downloads/downloads/subtitle_backups:/backup:rw
